# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aric Chokey | Data Journalist and Developer
email: achokey21@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aric Chokey is a journalist and developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "aricchokey.com" # the base hostname & protocol for your site
twitter_username: aric_chokey
github_username:  aachokey
resume_link: "https://drive.google.com/file/d/1bTSpUypmBurnhI9rXf9Gzw2mrbOgENbQ"

# Build settings
markdown: kramdown
